require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "Guardfile"
    - "**/*.gemspec"
    - "spec/**/*.rb"

Rails/ApplicationRecord:
  Exclude:
    - "spec/**/*.rb"
