name: Continuous Integration

on:
  push:
    branches: [master, develop, feature/workflows]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Update Bundler
      run: gem install bundler:2.0.2
    - name: Bundle install
      run: |
        bundle config deployment true
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run specs
      run: bundle exec rake spec
    - name: Check code style with Rubocop
      run: bundle exec rubocop
