name: publish

on:
  release:
    types: [published]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest

    needs: tests

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        rubygems: latest
        bundler-cache: true

    - uses: rubygems/release-gem@v1
