on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  test:
    name: Run specs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        rubygems: latest
        bundler-cache: true

    - name: Run specs
      run: bin/rspec

    - uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: coverage

  coverage:
    name: Report code coverage
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: code-coverage
        path: coverage

    - uses: paambaati/codeclimate-action@v5
      with:
        coverageLocations: |
          ${{ github.workspace }}/coverage/.resultset.json:simplecov
